FormKey: 026EEF:Mantella.esp
MajorRecordFlagsRaw: 8208
VersionControl: 12535
EditorID: MantellaResizeSettingsTerminal
Fallout4MajorRecordFlags:
- 0x10
- 0x2000
VirtualMachineAdapter:
  ScriptFragments:
    Script:
      Name: Fragments:Terminals:TERM_MantellaResizeSettingsT_07026EEF
      Properties:
      - MutagenObjectType: ScriptObjectProperty
        Name: MantellaQuest
        Object: 000F99:Mantella.esp
    Fragments:
    - FragmentIndex: 9
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaResizeSettingsT_07026EEF
      FragmentName: Fragment_Terminal_09
    - FragmentIndex: 2
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaResizeSettingsT_07026EEF
      FragmentName: Fragment_Terminal_02
    - FragmentIndex: 10
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaResizeSettingsT_07026EEF
      FragmentName: Fragment_Terminal_10
    - FragmentIndex: 1
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaResizeSettingsT_07026EEF
      FragmentName: Fragment_Terminal_01
    - FragmentIndex: 3
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaResizeSettingsT_07026EEF
      FragmentName: Fragment_Terminal_03
ObjectBounds:
  First: -18, -52, 86
  Second: 21, 0, 135
HeaderText:
  TargetLanguage: English
  Value: Mantella - Image Resize Settings
Name:
  TargetLanguage: English
  Value: '[Settings] Mantella Settings'
Model:
  File: Furniture\Terminals\TerminalWall01.nif
  Data: 0x0400000000000000000000000000000000000000
Keywords:
- 0A56D7:Fallout4.esm
- 06D5BB:Fallout4.esm
- 0C2022:Fallout4.esm
PNAM: 0xCC4C3300
FNAM: 0x0000
Holotapes: []
Flags:
- HasModel
WorkbenchData: 0x00
MarkerModel: Markers\MarkerWallTerminal3rdP.nif
MarkerParameters:
- Enabled: True
  Offset: 0, -86, 0
  EntryTypes:
  - Front
  - Behind
  - Right
  - Left
  - Other
  - 0x20
  - 0x40
  - 0x80
  Unknown: 0xFFFFFF
BodyTexts:
- Text:
    TargetLanguage: English
    Value: >-
      Choose option from the below for the value you want to use by Mantella Software when resizing images before sending them to the LLM. If the resolution chosen is larger than the actual width screen resolution then the image will be left untouched.

       A higher resolution will spend more tokens and have longer response times but will be more precise. A lower resolution mean the LLM might miss details such as small text when analysing the image.
MenuItems:
- ItemText:
    TargetLanguage: English
    Value: 512x512
  Type: DisplayText
  ItemId: 9
  DisplayText:
    TargetLanguage: English
    Value: >+
      Mantella Software will now resize images sent to the LLM to 512x512
  Conditions:
  - MutagenObjectType: ConditionFloat
    CompareOperator: NotEqualTo
    ComparisonValue: 512
    Data:
      MutagenObjectType: FunctionConditionData
      Function: GetVMQuestVariable
      ParameterOneRecord: 000F99:Mantella.esp
      ParameterOneNumber: 16781209
      ParameterTwoRecord: 167ED8:Mantella.esp
      ParameterTwoNumber: -1391034664
      ParameterTwoString: ::visionResize_var
- ItemText:
    TargetLanguage: English
    Value: 1024x1024 (recommended)
  Type: DisplayText
  ItemId: 10
  DisplayText:
    TargetLanguage: English
    Value: >+
      Mantella Software will now resize images sent to the LLM to 1024x1024
  Conditions:
  - MutagenObjectType: ConditionFloat
    CompareOperator: NotEqualTo
    ComparisonValue: 1024
    Data:
      MutagenObjectType: FunctionConditionData
      Function: GetVMQuestVariable
      ParameterOneRecord: 000F99:Mantella.esp
      ParameterOneNumber: 16781209
      ParameterTwoRecord: 167ED0:Mantella.esp
      ParameterTwoNumber: -1391034672
      ParameterTwoString: ::visionResize_var
- ItemText:
    TargetLanguage: English
    Value: 1536x1536
  Type: DisplayText
  ItemId: 1
  DisplayText:
    TargetLanguage: English
    Value: >+
      Mantella Software will now resize images sent to the LLM to 1536x1536
  Conditions:
  - MutagenObjectType: ConditionFloat
    CompareOperator: NotEqualTo
    ComparisonValue: 1536
    Data:
      MutagenObjectType: FunctionConditionData
      Function: GetVMQuestVariable
      ParameterOneRecord: 000F99:Mantella.esp
      ParameterOneNumber: 16781209
      ParameterTwoRecord: 167EC8:Mantella.esp
      ParameterTwoNumber: -1391034680
      ParameterTwoString: ::visionResize_var
- ItemText:
    TargetLanguage: English
    Value: 2048x2048
  Type: DisplayText
  ItemId: 2
  DisplayText:
    TargetLanguage: English
    Value: >+
      Mantella Software will now resize images sent to the LLM to 2048x2048

  Conditions:
  - MutagenObjectType: ConditionFloat
    CompareOperator: NotEqualTo
    ComparisonValue: 2048
    Data:
      MutagenObjectType: FunctionConditionData
      Function: GetVMQuestVariable
      ParameterOneRecord: 000F99:Mantella.esp
      ParameterOneNumber: 16781209
      ParameterTwoRecord: 167EC0:Mantella.esp
      ParameterTwoNumber: -1391034688
      ParameterTwoString: ::visionResize_var
- ItemText:
    TargetLanguage: English
    Value: 2560x2560
  Type: DisplayText
  ItemId: 3
  DisplayText:
    TargetLanguage: English
    Value: >+
      Mantella Software will now resize images sent to the LLM to 2560x2560

  Conditions:
  - MutagenObjectType: ConditionFloat
    CompareOperator: NotEqualTo
    ComparisonValue: 2560
    Data:
      MutagenObjectType: FunctionConditionData
      Function: GetVMQuestVariable
      ParameterOneRecord: 000F99:Mantella.esp
      ParameterOneNumber: 16781209
      ParameterTwoRecord: 167EB8:Mantella.esp
      ParameterTwoNumber: -1391034696
      ParameterTwoString: ::visionResize_var
MajorFlags:
- 0x10
- 0x2000
